name: Auto Commit

on:
  schedule:
    - cron: "0 0 * * *"  # 12:00 AM UTC (03:00 AM Somalia)

permissions:
  contents: write   # MUHIIM si push u shaqeeyo

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Dummy Commit
        run: |
          date > date.txt
          git config user.name "somiaapdalla"
          git config user.email "somiadesu2003@gmail.com"
          git add date.txt
          git commit -m "Automated commit to keep streak alive" || echo "No changes to commit"
          git push
